# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: self-hosted

variables:
  DOCKER_USER: 'ivankhodyrev'
  IMAGE: 'hello-app:$(Build.BuildId)''

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: |
              docker build -t $(IMAGE) .
            displayName: 'Build Image'
            workingDirectory: $(Build.SourcesDirectory)
  - stage: PushImage
    dependsOn: Build
    jobs:
      - job: PushImageJob
        steps:
          - script: |
              docker login -u $(DOCKER_USER) -p $(DOCKER_TOKEN)
              docker push $(DOCKER_USER)/$(IMAGE)
            displayName: 'Push Image'