# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: self-hosted

stages:
  - stage: checkout
    jobs:
      - job: CheckoutJob
        steps:
          - script: |
              ls -la $(Build.SourcesDirectory)
              echo "the repo is here"
            displayName: 'Check repo'

  - stage: build
    jobs:
      - job: BuildJob
        steps:
          - script: |
              docker build -t hello-app:$(Build.BuildId) $(Build.SourcesDirectory)
            displayName: 'Build Image'
