services:
  hello-app:
    build: .
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  ws:
    image: caddy:2-alpine
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - hello-app